services:
    backend:
        container_name: backend-${UUID}
        build:
            context: ./backend
            dockerfile: Dockerfile
            target: development
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        env_file:
            - .env.dev
        volumes:
            - ./backend/src:/backend/src
            - backend-gradle:/backend/.gradle
        networks:
            - common-network
        depends_on:
            - postgres
            - redis

    frontend:
        container_name: frontend-${UUID}
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: development
        ports:
            - "${FRONTEND_PORT}:${FRONTEND_PORT}"
        env_file:
            - .env.dev
        volumes:
            - ./frontend/:/app/
            - ./frontend/package.json:/app/package.json
            - ./frontend/package-lock.json:/app/package-lock.json
            - frontend:/app/node_modules
        environment:
            WATCHPACK_POLLING: true
        networks:
            - common-network

    postgres:
        container_name: postgres-${UUID}
        image: postgres:17
        environment:
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - common-network

    pgadmin:
        image: dpage/pgadmin4:9.8.0
        container_name: pgadmin-${UUID}
        ports:
            - 8888:80
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - postgres
        networks:
            - common-network

    redis:
        container_name: redis-${UUID}
        image: redis:8.2-alpine
        expose:
            - "${REDIS_PORT}"
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis-data:/data
        networks:
            - common-network

    redis-insight:
        container_name: redis-insight-${UUID}
        image: redis/redisinsight:latest
        ports:
            - 5540:5540
        volumes:
            - redis-insight-data:/db
        depends_on:
            - redis
        networks:
            - common-network

volumes:
    frontend:
    backend-gradle:
    postgres-data:
    pgadmin-data:
    redis-data:
    redis-insight-data:

networks:
    common-network:
        driver: bridge
